/**
 * Zásobník jmen regionů. Je záměrně větší než největší mapa, kterou
 * generátor postaví, aby se jména neopakovala.
 */
export const REGION_NAMES: readonly string[] = [
  'Údolí králů',
  'Vlčí hvozd',
  'Stříbrná stráň',
  'Zelené údolí',
  'Jižní mokřady',
  'Severní pláně',
  'Kamenná brána',
  'Medová luka',
  'Jižní brod',
  'Ledový hřeben',
  'Rudné hory',
  'Doubrava',
  'Zlatý potok',
  'Orlí štít',
  'Černý les',
  'Východní step',
  'Západní břeh',
  'Rybářské zátoky',
  'Solné pobřeží',
  'Mlžná kotlina',
  'Sokolí skály',
  'Bílá pahorkatina',
  'Trnová pustina',
  'Jantarová zátoka',
  'Havraní vrch',
  'Modré jezero',
  'Tichá rokle',
  'Uhelný hřbet',
  'Lovecké revíry',
  'Kovářská výspa',
  'Bouřné útesy',
  'Slunečná plošina',
  'Vraní bažiny',
  'Kaštanový háj',
  'Studená sedla',
  'Perlový přístav',
  'Divoký brod',
  'Šeptající bory',
  'Rezavé skály',
  'Královská cesta',
  'Liščí kopce',
  'Zapomenutá tvrz',
  'Písečné duny',
  'Hraniční valy',
  'Medvědí soutěska',
  'Klidné pobřeží',
  'Obsidiánový sráz',
  'Vinné terasy',
];
